# Default initial positions for manipuation_environment's ros2_control fake system

initial_positions:
  robot1_joint1: 0
  robot1_joint2: 0
  robot1_joint3: 0
  robot1_joint4: 0
  robot1_joint5: 0
  robot1_joint6: 0