# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - xarm6_controller

  xarm6_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot1_joint1
      - robot1_joint2
      - robot1_joint3
      - robot1_joint4
      - robot1_joint5
      - robot1_joint6
    action_ns: follow_joint_trajectory
    default: true